// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxQzd36H8cGjQM_7Bb3fhXPCF8BHbEaaY',
    appId: '1:480647790824:android:05249a9639dde7a68e895d',
    messagingSenderId: '480647790824',
    projectId: 'expanse-tracker-app-2d7e4',
    storageBucket: 'expanse-tracker-app-2d7e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3sSt-ojRR4r64jYJUfDLrhEgJaFnX2j0',
    appId: '1:480647790824:ios:f7da36427a59a8068e895d',
    messagingSenderId: '480647790824',
    projectId: 'expanse-tracker-app-2d7e4',
    storageBucket: 'expanse-tracker-app-2d7e4.firebasestorage.app',
    androidClientId: '480647790824-id9c88rcuh764bng3ij5ccnmra6dn83j.apps.googleusercontent.com',
    iosClientId: '480647790824-8e827tqtoglceih1tlvf99o2rd4th6q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapbilling',
  );
}
